// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Plugins() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<h1 class=\"text-3xl font-semibold mb-8\">Plugins</h1><div class=\"bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden\"><table class=\"w-full text-sm\"><thead class=\"bg-zinc-950\"><tr><th class=\"px-6 py-4 text-left\">ID</th><th class=\"px-6 py-4 text-left\">Name</th><th class=\"px-6 py-4 text-left\">Kind</th><th class=\"px-6 py-4 text-left\">Status</th></tr></thead> <tbody class=\"divide-y divide-zinc-800\"><tr><td class=\"px-6 py-4 font-mono text-xs\">dashboard</td><td class=\"px-6 py-4\">Dashboard</td><td class=\"px-6 py-4\"><span class=\"px-2 py-0.5 text-xs bg-blue-500/10 text-blue-400 rounded\">ui</span></td><td class=\"px-6 py-4\"><span class=\"text-emerald-400\">running</span></td></tr><tr><td class=\"px-6 py-4 font-mono text-xs\">mock-input</td><td class=\"px-6 py-4\">Mock Input</td><td class=\"px-6 py-4\"><span class=\"px-2 py-0.5 text-xs bg-zinc-700 rounded\">input</span></td><td class=\"px-6 py-4\"><span class=\"text-emerald-400\">running</span></td></tr><tr><td class=\"px-6 py-4 font-mono text-xs\">mock-ai</td><td class=\"px-6 py-4\">Mock AI</td><td class=\"px-6 py-4\"><span class=\"px-2 py-0.5 text-xs bg-purple-500/10 text-purple-400 rounded\">ai</span></td><td class=\"px-6 py-4\"><span class=\"text-emerald-400\">running</span></td></tr></tbody></table></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Plugins").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
