// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Sessions() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex items-center justify-between mb-8\"><h1 class=\"text-3xl font-semibold\">Sessions</h1><div class=\"text-sm text-zinc-400\">2 active</div></div><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><div class=\"bg-zinc-900 border border-zinc-800 rounded-2xl p-6\"><div class=\"flex items-center justify-between mb-4\"><div><div class=\"font-semibold\">WhatsApp / João</div><div class=\"text-xs text-zinc-500\">session_mock_001</div></div><span class=\"text-xs text-emerald-400\">active</span></div><div class=\"text-sm text-zinc-400\">Last message: “Fechado, te aviso em seguida.”</div><div class=\"text-xs text-zinc-500 mt-4\">Messages: 14 • Suggestions: 3</div></div><div class=\"bg-zinc-900 border border-zinc-800 rounded-2xl p-6\"><div class=\"flex items-center justify-between mb-4\"><div><div class=\"font-semibold\">Telegram / Client</div><div class=\"text-xs text-zinc-500\">session_mock_002</div></div><span class=\"text-xs text-amber-400\">waiting</span></div><div class=\"text-sm text-zinc-400\">Last message: “Can you send the proposal?”</div><div class=\"text-xs text-zinc-500 mt-4\">Messages: 7 • Suggestions: 1</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Sessions").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
